[package]
name = "dwmstatus"
version = "0.1.0"
authors = ["George Macon <george.macon@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "^0.4.6"
error-chain = "^0.12.0"
regex = "^1.0.5"
lazy_static = "^1.1.0"
sensors = "^0.2.1"
systemstat = "^0.1.3"
xcb = "^0.8.1"
